export const data = [
    {
        id: 1,
        index: 1,
        visitDate: '2024-12-01',
        days: 3,
        week: 29,
        'Maternal Age': 27,
        'Maternal Height': 165,
        'Maternal Weight': 55,
        Gender: 'F',
        Hypertension: 'NO',
    },
    {
        id: 2,
        index: 2,
        visitDate: '2024-12-02',
        days: 5,
        week: 30,
        'Maternal Age': 30,
        'Maternal Height': 162,
        'Maternal Weight': 60,
        Gender: 'F',
        Hypertension: 'YES',
    },
    {
        id: 3,
        index: 3,
        visitDate: '2024-12-03',
        days: 1,
        week: 31,
        'Maternal Age': 28,
        'Maternal Height': 170,
        'Maternal Weight': 58,
        Gender: 'M',
        Hypertension: 'NO',
    },
    {
        id: 4,
        index: 4,
        visitDate: '2024-12-04',
        days: 6,
        week: 32,
        'Maternal Age': 26,
        'Maternal Height': 160,
        'Maternal Weight': 52,
        Gender: 'F',
        Hypertension: 'NO',
    },
    {
        id: 5,
        index: 5,
        visitDate: '2024-12-05',
        days: 2,
        week: 33,
        'Maternal Age': 29,
        'Maternal Height': 155,
        'Maternal Weight': 50,
        Gender: 'F',
        Hypertension: 'YES',
    },
    {
        id: 6,
        index: 6,
        visitDate: '2024-12-06',
        days: 4,
        week: 34,
        'Maternal Age': 25,
        'Maternal Height': 168,
        'Maternal Weight': 54,
        Gender: 'M',
        Hypertension: 'NO',
    },
    {
        id: 7,
        index: 7,
        visitDate: '2024-12-07',
        days: 0,
        week: 35,
        'Maternal Age': 32,
        'Maternal Height': 159,
        'Maternal Weight': 59,
        Gender: 'F',
        Hypertension: 'NO',
    },
    {
        id: 8,
        index: 8,
        visitDate: '2024-12-08',
        days: 3,
        week: 36,
        'Maternal Age': 31,
        'Maternal Height': 161,
        'Maternal Weight': 57,
        Gender: 'M',
        Hypertension: 'YES',
    },
    {
        id: 9,
        index: 9,
        visitDate: '2024-12-09',
        days: 2,
        week: 37,
        'Maternal Age': 29,
        'Maternal Height': 166,
        'Maternal Weight': 56,
        Gender: 'F',
        Hypertension: 'NO',
    },
    {
        id: 10,
        index: 10,
        visitDate: '2024-12-10',
        days: 1,
        week: 38,
        'Maternal Age': 30,
        'Maternal Height': 164,
        'Maternal Weight': 62,
        Gender: 'M',
        Hypertension: 'NO',
    },
    {
        id: 11,
        index: 11,
        visitDate: '2024-12-11',
        days: 5,
        week: 39,
        'Maternal Age': 27,
        'Maternal Height': 167,
        'Maternal Weight': 63,
        Gender: 'F',
        Hypertension: 'YES',
    },
    {
        id: 12,
        index: 12,
        visitDate: '2024-12-12',
        days: 4,
        week: 40,
        'Maternal Age': 26,
        'Maternal Height': 158,
        'Maternal Weight': 51,
        Gender: 'M',
        Hypertension: 'NO',
    },
];
